In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt 
import pytesseract

In [2]:
import os
from pdf2image import convert_from_path

def convert_pdf_jpg(path_dir):
    for pdf_file in os.listdir(path_dir):

        if pdf_file.endswith(".pdf"):

            pages = convert_from_path(pdf_file, 300)
            pdf_file = pdf_file[:-4]

            for page in pages:

               page.save("%s-page%d.jpg" % (pdf_file,pages.index(page)), "JPEG")

# path_pdf=r'c:\\Users\\Admin\\Desktop\\ComputerVision\\OCR\\dataapp'
# convert_pdf_jpg(path_pdf)

In [14]:
def preprocessing_2(image):
    img=cv.imread(image)
    #img_gray=cv.cvtColor(img,cv.COLOR_BGR2GRAY)
    #image_tresh=cv.threshold(img_gray,0,255,cv.THRESH_BINARY_INV + cv.THRESH_OTSU)[1]
    return img

def preprocessing_3(image):
    img = cv.imread(image)
    #cv.imshow("Original image",img)
    # CLAHE (Contrast Limited Adaptive Histogram Equalization)
    clahe = cv.createCLAHE(clipLimit=3., tileGridSize=(8,8))

    lab = cv.cvtColor(img, cv.COLOR_BGR2LAB)  # convert from BGR to LAB color space
    l, a, b = cv.split(lab)  # split on 3 different channels

    l2 = clahe.apply(l)  # apply CLAHE to the L-channel

    lab = cv.merge((l2,a,b))  # merge channels
    img2 = cv.cvtColor(lab, cv.COLOR_LAB2BGR)  # convert from LAB to BGR (image constraste)
    return img2


def display(im_path):
    dpi = 50
    im_data = plt.imread(im_path)

    height, width  = im_data.shape[:2]
    
    # What size does the figure need to be in inches to fit the image?
    figsize = width / float(dpi), height / float(dpi)

    # Create a figure of the right size with one axes that takes up the full figure
    fig = plt.figure(figsize=figsize)
    ax = fig.add_axes([0, 0, 1, 1])

    # Hide spines, ticks, etc.
    ax.axis('off')

    # Display the image.
    ax.imshow(im_data, cmap='gray')

    plt.show()

def display_img(title, img):
    """Displays an image on screen and maintains the output until the user presses a key"""
    cv.namedWindow('img', cv.WINDOW_NORMAL)
    cv.setWindowTitle('img', title)
    cv.resizeWindow('img', 1200, 900)
    # Display Image on screen
    cv.imshow('img', img)
    # Mantain output until user presses a key
    cv.waitKey(0)
    # Destroy windows when user presses a key
    cv.destroyAllWindows()

In [15]:
import keras_ocr
import pandas as pd 

path='dataapp/test_page_0.jpg'
img1=preprocessing_2(path)
img2=preprocessing_3(path)

def x_keras_ocr(image):
    pipeline = keras_ocr.pipeline.Pipeline()
    results = pipeline.recognize([image])
    data_process_keras=pd.DataFrame(results[0], columns=['text','bbox'])

    return results,data_process_keras

In [12]:
results_process_keras_1,data_process_keras_1=x_keras_ocr(img2)
data_process_keras_1.to_excel('dataapp/preprocess_3/keras_ocr_process_1.xlsx')
data_process_keras_1

Looking for C:\Users\Admin\.keras-ocr\craft_mlt_25k.h5
Looking for C:\Users\Admin\.keras-ocr\crnn_kurapan.h5
1/1 [==============================] - 218s 218s/step
8/8 [==============================] - 163s 16s/step

           text                                               bbox
0     cordenies  [[2645.457, 352.95605], [2700.2852, 352.95605]...
1         dzang  [[1545.4678, 383.79688], [1590.0156, 383.79688...
2           ote  [[1610.5762, 383.79688], [1644.8438, 383.79688...
3          aems  [[2628.3232, 400.93066], [2700.2852, 400.93066...
4         opade  [[1391.2637, 411.21094], [1439.2383, 411.21094...
..          ...                                                ...
221        tile  [[3286.2607, 2350.7559], [3351.3691, 2350.7559...
222  firnisseur  [[3221.1523, 2378.17], [3347.9424, 2378.17], [...
223          b0  [[3437.038, 2378.17], [3457.5986, 2378.17], [3...
224         ans  [[3186.8848, 2381.5967], [3217.7256, 2381.5967...
225        tene  [[3330.8086, 2398.7305], [3423.331, 2398.7305]...

[226 rows x 2 columns]

In [24]:
ocr_img_1 = results_process_keras_1[0]
for text, box in ocr_img_1:
    print(text)

cordenies
dzang
ote
aems
opade
se
seklke
czaob
tot
opaon
ozadt
oeade
54
8s
f5s
dzaoe
185
t
czae
gae
ozans
te
5
20
21
27
22
dza02
tze
15
j
a
24
45
danz
didoa
didoi
daol
st
8b
11
sh
a
section
view
il
29
59
section
view
jj
detail
scale
26
d
scale
2xl
s0
scale
211
detail
s1
scale
2
211
t
amin
3
3
owin
durn
sa
55
56
section
view
ese
57
scale
211
section
view
fle
30
scale
2a1
ao
12
detail
45
scale
21
detail
scale
241
so
sz
53
section
view
g
view
section
heh
sd
scale
28
scale
261
axonometric
view
s5
scale
shin
s6
5t
spooogn
adhelive
tape
ec
maite
31zatb51s
s0
efooogles
lee
epdy
galy
55
seasteee
pooogtss
trrees
go
ficoaa
lee
ia
edtec
dantle
ol
eoooosss
bip
notes
912121210
table
lauer
tal
see
oone
ougdn
efooosseo
clip
lanicus
chhoce
use
teiperatlres
joc
to
betc
cotaod
gaatss
connections
hose
must
not
lear
operating
spoarets
ga
straigt
ccakectoe
ditions
picd
la
oels
65
efooogi
unspecitied
dilensions
taren
datas
fbon
ctald
checion
gse2
siee
st
oial
vass
siesg
denauinalioh
referencia
leer
fanu
leighnt
art
hunbe
tube
maqd01797
plat
kaue
naterial
cilca
bt
cd
feat
loleer
aua
reteeen
otoog
eoneoal
cee
69g
utan
laves
vttre
rree
class
taeh
rooz
4bales
eneuee
gie
tile
firnisseur
b0
ans
tene

In [16]:
results_process_keras_2,data_process_keras_2=x_keras_ocr(img1)
data_process_keras_2.to_excel('dataapp/preprocess_3/keras_ocr_process_2.xlsx')
data_process_keras_2

Looking for C:\Users\Admin\.keras-ocr\craft_mlt_25k.h5
Looking for C:\Users\Admin\.keras-ocr\crnn_kurapan.h5
1/1 [==============================] - 79s 79s/step
8/8 [==============================] - 154s 17s/step

          text                                               bbox
0           lo  [[3440.4648, 332.3955], [3457.5986, 332.3955],...
1     cordenis  [[2645.457, 352.95605], [2700.2852, 352.95605]...
2         alee  [[2813.3682, 380.37012], [2857.916, 380.37012]...
3        dzang  [[1545.4678, 383.79688], [1590.0156, 383.79688...
4          ote  [[1610.5762, 383.79688], [1644.8438, 383.79688...
..         ...                                                ...
230        tle  [[3286.2607, 2350.7559], [3351.3691, 2350.7559...
231  fenissfur  [[3221.1523, 2378.17], [3347.9424, 2378.17], [...
232        ael  [[3186.8848, 2381.5967], [3217.7256, 2381.5967...
233         oo  [[3437.038, 2381.5967], [3457.5986, 2381.5967]...
234      tenee  [[3330.8086, 2398.7305], [3423.331, 2398.7305]...

[235 rows x 2 columns]

In [18]:
ocr_img_2 = results_process_keras_2[0]
for text, box in ocr_img_2:
    print(text)

lo
cordenis
alee
dzang
ote
2
aerre
oaade
oz
13
sielke
czrob
tot
a
opadn
bzaot
5
oead
54
8s
f
16
dzaoe
ee
t
ozroe
gae
dzans
te
5
20
21
z
22
dzacz
tze
7
7
za
2a
s
45
pidoa
dienz
didot
dno
7
st
b
t
7
sh

section
view
ii
59
section
view
29
jej
detail
scale
2r
9
scale
25
s0
scale
211
51
detail
s1
2
scale
27i
t
min
8
3
lomin
nin
sa
55
55
56
ss
section
vien
eve
57
scale
211
section
view
flf
5
s0
scale
2al
12
detail
45
scale
2hl
detail
scale
241
so
sz
53
section
view
g
view
section
eh
scale
20
scale
251
axonometric
view
s5
scale
saio
s6
epogoegr
adheslye
tlpe
poc
maite
71631s
efooogiss
lee
epdy
galy
seasteee
pooogtss
tureeee
ficoal
lee
170a
sedstec
bats
ltrains
epoooosss
lip
notes
512121210
laerleal
see
oone
taale
ougdd
efooosseo
clip
chhcce
afiols
use
teiperatlres
joc
to
b5tc
cotaod
geeats8
hose
conections
must
not
lear
operating
coleel
spoaaets
ga
staaigt
ccahectoe
ditions
dicd
saaeass
slels
6s
efooogi
unspecitied
dilensions
taken
datas
fbon
ctalc
dhecton
ge2
giee
t
oial
wasse
siesg
dewnincion
leer
fanu
hefenehcin
leigint
rrt
huneee
tube
maqd01797
plat
kaue
aterial
colca
oi
bt
cd
feat
doleer
mua
reteeien
otoog
eonedas
dee
69g
ufau
laved
tttre
riee
class
taeh
rodz
1bb1es
seaauot
tio
tle
fenissfur
ael
oo
tenee

In [1]:
plt.figure(figsize=(16,16))
keras_plt = keras_ocr.tools.drawBoxes(image = img2, boxes = results_process_keras_2[0], boxes_format = 'predictions')
plt.imshow(keras_plt)

In [2]:
plt.figure(figsize=(16,16))
keras_plt_1 = keras_ocr.tools.drawBoxes(image = img1, boxes = results_process_keras_1[0], boxes_format = 'predictions')
plt.imshow(keras_plt_1)